version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
    - "jennyEckstein"
    - "eaviles"
    - "BizzlePop34"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
    - "jennyEckstein"
    - "eaviles"
    - "BizzlePop34"
  