name: Github Action Merge Dependabot
uses: fastify/github-action-merge-dependabot@v1.1.1

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  check:
    name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10, 12, 14, 15]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
      - name: Install
        run: npm ci --loglevel=error
        env:
          DISABLE_OPENCOLLECTIVE: true
      - name: Run linter
        run: npm run eslint
      - name: Run tests
        run: npm test -- --ci --runInBand
        env:
          CI: true
  automerge:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v1
        if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
        with:
          github-token: ${{secrets.github_token}}